// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vvvlyokntgjhitubaasp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ2dmx5b2tudGdqaGl0dWJhYXNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2MzgyOTYsImV4cCI6MjA2MDIxNDI5Nn0.-YyFLhUYZ3kBgpWUY6KGYhCwljJ0XWnkRMafVUBFzKQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);