
import { useState, useEffect } from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { CalculatorNumberInput } from "@/components/calculator/calculator-number-input";
import { CalculatorResult, ResultAlert } from "@/components/calculator/calculator-result";

export function BMICalculator() {
  // Metric system
  const [heightCm, setHeightCm] = useState<number>(170);
  const [weightKg, setWeightKg] = useState<number>(70);
  
  // Imperial system
  const [heightFt, setHeightFt] = useState<number>(5);
  const [heightIn, setHeightIn] = useState<number>(7);
  const [weightLbs, setWeightLbs] = useState<number>(154);
  
  const [bmi, setBmi] = useState<number | null>(null);
  const [bmiCategory, setBmiCategory] = useState<string>("");
  const [system, setSystem] = useState<"metric" | "imperial">("metric");

  // Calculate BMI when values change
  useEffect(() => {
    calculateBMI();
  }, [heightCm, weightKg, heightFt, heightIn, weightLbs, system]);

  const calculateBMI = () => {
    let calculatedBMI: number;
    
    if (system === "metric") {
      // BMI = weight (kg) / (height (m))^2
      const heightInMeters = heightCm / 100;
      calculatedBMI = weightKg / (heightInMeters * heightInMeters);
    } else {
      // BMI = (weight (lbs) * 703) / (height (in))^2
      const heightInInches = (heightFt * 12) + heightIn;
      calculatedBMI = (weightLbs * 703) / (heightInInches * heightInInches);
    }
    
    calculatedBMI = parseFloat(calculatedBMI.toFixed(1));
    setBmi(calculatedBMI);
    
    // Determine BMI category
    if (calculatedBMI < 18.5) {
      setBmiCategory("Underweight");
    } else if (calculatedBMI >= 18.5 && calculatedBMI < 25) {
      setBmiCategory("Normal weight");
    } else if (calculatedBMI >= 25 && calculatedBMI < 30) {
      setBmiCategory("Overweight");
    } else {
      setBmiCategory("Obesity");
    }
  };

  const getAlertType = () => {
    if (!bmi) return "info";
    if (bmi < 18.5) return "warning";
    if (bmi >= 18.5 && bmi < 25) return "success";
    if (bmi >= 25 && bmi < 30) return "warning";
    return "error";
  };

  const downloadReport = () => {
    if (!bmi) return;
    
    const height = system === "metric" 
      ? `${heightCm} cm` 
      : `${heightFt}'${heightIn}"`;
    
    const weight = system === "metric"
      ? `${weightKg} kg`
      : `${weightLbs} lbs`;
    
    const report = `
BMI CALCULATION REPORT
---------------------
Date: ${new Date().toLocaleDateString()}

YOUR MEASUREMENTS:
Height: ${height}
Weight: ${weight}

RESULTS:
BMI Value: ${bmi}
Category: ${bmiCategory}

INTERPRETATION:
${getBmiInterpretation(bmiCategory)}

BMI CATEGORIES:
- Underweight: BMI less than 18.5
- Normal weight: BMI 18.5–24.9
- Overweight: BMI 25–29.9
- Obesity: BMI 30 or greater

Note: BMI is a screening tool but does not diagnose body fatness or health.
For a complete health assessment, please consult a healthcare provider.

Generated by: Vital Metrics Health Calculator
`;

    const blob = new Blob([report], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `bmi-report-${new Date().toLocaleDateString().replace(/\//g, '-')}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const getBmiInterpretation = (category: string) => {
    switch(category) {
      case "Underweight":
        return "Your BMI indicates you may be underweight. Consider consulting with a healthcare professional.";
      case "Normal weight":
        return "Your BMI indicates you are at a healthy weight. Maintain a balanced diet and regular physical activity.";
      case "Overweight":
        return "Your BMI indicates you may be overweight. Consider adopting healthier eating habits and increasing physical activity.";
      case "Obesity":
        return "Your BMI indicates obesity. It's recommended to consult with a healthcare professional for personalized advice.";
      default:
        return "";
    }
  };

  return (
    <div className="space-y-6">
      <Card>
        <CardHeader>
          <CardTitle>BMI Calculator</CardTitle>
          <CardDescription>
            Body Mass Index (BMI) is a measure of body fat based on height and weight that applies to adult men and women.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <Tabs value={system} onValueChange={(v) => setSystem(v as "metric" | "imperial")}>
            <TabsList className="grid w-full grid-cols-2">
              <TabsTrigger value="metric">Metric</TabsTrigger>
              <TabsTrigger value="imperial">Imperial</TabsTrigger>
            </TabsList>
            <TabsContent value="metric" className="space-y-4">
              <CalculatorNumberInput
                label="Height"
                value={heightCm}
                onChange={setHeightCm}
                min={50}
                max={250}
                step={1}
                unit="cm"
                description="50-250 cm"
                required
              />
              <CalculatorNumberInput
                label="Weight"
                value={weightKg}
                onChange={setWeightKg}
                min={20}
                max={300}
                step={0.1}
                unit="kg"
                description="20-300 kg"
                required
              />
            </TabsContent>
            <TabsContent value="imperial" className="space-y-4">
              <div className="grid grid-cols-2 gap-4">
                <CalculatorNumberInput
                  label="Height (feet)"
                  value={heightFt}
                  onChange={setHeightFt}
                  min={1}
                  max={8}
                  step={1}
                  unit="ft"
                  required
                />
                <CalculatorNumberInput
                  label="Height (inches)"
                  value={heightIn}
                  onChange={setHeightIn}
                  min={0}
                  max={11}
                  step={1}
                  unit="in"
                  required
                />
              </div>
              <CalculatorNumberInput
                label="Weight"
                value={weightLbs}
                onChange={setWeightLbs}
                min={44}
                max={660}
                step={0.1}
                unit="lbs"
                description="44-660 lbs"
                required
              />
            </TabsContent>
          </Tabs>
        </CardContent>
      </Card>

      {bmi !== null && (
        <CalculatorResult 
          title="Your BMI Result" 
          onDownload={downloadReport}
        >
          <div className="space-y-4">
            <div className="flex items-center justify-center">
              <div className="text-center">
                <div className="text-4xl font-bold">{bmi}</div>
                <div className="text-sm text-muted-foreground mt-1">BMI Value</div>
              </div>
            </div>
            
            <ResultAlert type={getAlertType()} title={`BMI Category: ${bmiCategory}`}>
              {getBmiInterpretation(bmiCategory)}
            </ResultAlert>
            
            <div className="text-sm text-muted-foreground">
              <p>BMI Categories:</p>
              <ul className="list-disc list-inside mt-1">
                <li>Underweight: BMI less than 18.5</li>
                <li>Normal weight: BMI 18.5–24.9</li>
                <li>Overweight: BMI 25–29.9</li>
                <li>Obesity: BMI 30 or greater</li>
              </ul>
              <p className="mt-2">
                Note: BMI is a screening tool but does not diagnose body fatness or health. Consult a healthcare provider for a health assessment.
              </p>
            </div>
          </div>
        </CalculatorResult>
      )}
    </div>
  );
}
