
import { useState, useEffect } from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Label } from "@/components/ui/label";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { CalculatorNumberInput } from "@/components/calculator/calculator-number-input";
import { CalculatorResult } from "@/components/calculator/calculator-result";

export function BMRCalculator() {
  const [gender, setGender] = useState<"male" | "female">("male");
  const [age, setAge] = useState<number>(30);
  const [system, setSystem] = useState<"metric" | "imperial">("metric");
  
  // Metric
  const [heightCm, setHeightCm] = useState<number>(175);
  const [weightKg, setWeightKg] = useState<number>(70);
  
  // Imperial
  const [heightFt, setHeightFt] = useState<number>(5);
  const [heightIn, setHeightIn] = useState<number>(9);
  const [weightLbs, setWeightLbs] = useState<number>(154);
  
  const [bmr, setBmr] = useState<number | null>(null);

  useEffect(() => {
    calculateBMR();
  }, [gender, age, heightCm, weightKg, heightFt, heightIn, weightLbs, system]);

  const calculateBMR = () => {
    let height: number; // in cm
    let weight: number; // in kg
    
    if (system === "metric") {
      height = heightCm;
      weight = weightKg;
    } else {
      // Convert feet and inches to cm
      height = ((heightFt * 12) + heightIn) * 2.54;
      // Convert lbs to kg
      weight = weightLbs * 0.453592;
    }
    
    // Mifflin-St Jeor Formula for BMR
    let calculatedBMR: number;
    if (gender === "male") {
      // For men: BMR = 10 × weight(kg) + 6.25 × height(cm) - 5 × age(years) + 5
      calculatedBMR = 10 * weight + 6.25 * height - 5 * age + 5;
    } else {
      // For women: BMR = 10 × weight(kg) + 6.25 × height(cm) - 5 × age(years) - 161
      calculatedBMR = 10 * weight + 6.25 * height - 5 * age - 161;
    }
    
    calculatedBMR = Math.round(calculatedBMR);
    setBmr(calculatedBMR);
  };

  const downloadReport = () => {
    if (!bmr) return;
    
    const height = system === "metric" 
      ? `${heightCm} cm` 
      : `${heightFt}'${heightIn}" (${((heightFt * 12) + heightIn) * 2.54} cm)`;
    
    const weight = system === "metric"
      ? `${weightKg} kg`
      : `${weightLbs} lbs (${(weightLbs * 0.453592).toFixed(1)} kg)`;
    
    const report = `
BASAL METABOLIC RATE CALCULATION REPORT (Mifflin-St Jeor Formula)
-----------------------------------------------------------------
Date: ${new Date().toLocaleDateString()}

YOUR INFORMATION:
Gender: ${gender === "male" ? "Male" : "Female"}
Age: ${age} years
Height: ${height}
Weight: ${weight}

RESULTS:
Basal Metabolic Rate (BMR): ${bmr} calories/day

DAILY CALORIE NEEDS BASED ON ACTIVITY LEVEL:
Sedentary (little or no exercise): ${Math.round(bmr * 1.2)} calories/day
Lightly active (light exercise 1-3 days/week): ${Math.round(bmr * 1.375)} calories/day
Moderately active (moderate exercise 3-5 days/week): ${Math.round(bmr * 1.55)} calories/day
Very active (hard exercise 6-7 days/week): ${Math.round(bmr * 1.725)} calories/day
Extremely active (very hard exercise & physical job): ${Math.round(bmr * 1.9)} calories/day

ABOUT THE MIFFLIN-ST JEOR FORMULA:
For men: BMR = 10 × weight(kg) + 6.25 × height(cm) - 5 × age(years) + 5
For women: BMR = 10 × weight(kg) + 6.25 × height(cm) - 5 × age(years) - 161

WHAT IS BMR?
Basal Metabolic Rate is the number of calories your body needs to maintain basic physiological
functions while at complete rest. This includes breathing, circulation, cell production,
nutrient processing, and protein synthesis. BMR represents the minimum amount of energy
needed to keep your body functioning.

Note: This calculation provides an estimate. Individual metabolism can vary based on genetic
factors, body composition, hormone function, and health status.

Generated by: Vital Metrics Health Calculator
`;

    const blob = new Blob([report], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `bmr-report-${new Date().toLocaleDateString().replace(/\//g, '-')}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6">
      <Card>
        <CardHeader>
          <CardTitle>BMR Calculator (Mifflin-St Jeor Formula)</CardTitle>
          <CardDescription>
            Calculate your Basal Metabolic Rate (BMR) using the Mifflin-St Jeor formula, which estimates the calories your body needs at complete rest.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="space-y-3">
            <Label>Gender</Label>
            <RadioGroup
              value={gender}
              onValueChange={(value) => setGender(value as "male" | "female")}
              className="flex space-x-4"
            >
              <div className="flex items-center space-x-2">
                <RadioGroupItem value="male" id="bmr-male" />
                <Label htmlFor="bmr-male">Male</Label>
              </div>
              <div className="flex items-center space-x-2">
                <RadioGroupItem value="female" id="bmr-female" />
                <Label htmlFor="bmr-female">Female</Label>
              </div>
            </RadioGroup>
          </div>

          <CalculatorNumberInput
            label="Age"
            value={age}
            onChange={setAge}
            min={15}
            max={100}
            step={1}
            unit="years"
            required
          />

          <Tabs value={system} onValueChange={(v) => setSystem(v as "metric" | "imperial")}>
            <TabsList className="grid w-full grid-cols-2">
              <TabsTrigger value="metric">Metric</TabsTrigger>
              <TabsTrigger value="imperial">Imperial</TabsTrigger>
            </TabsList>
            <TabsContent value="metric" className="space-y-4">
              <CalculatorNumberInput
                label="Height"
                value={heightCm}
                onChange={setHeightCm}
                min={120}
                max={250}
                step={1}
                unit="cm"
                required
              />
              <CalculatorNumberInput
                label="Weight"
                value={weightKg}
                onChange={setWeightKg}
                min={30}
                max={300}
                step={0.1}
                unit="kg"
                required
              />
            </TabsContent>
            <TabsContent value="imperial" className="space-y-4">
              <div className="grid grid-cols-2 gap-4">
                <CalculatorNumberInput
                  label="Height (feet)"
                  value={heightFt}
                  onChange={setHeightFt}
                  min={3}
                  max={8}
                  step={1}
                  unit="ft"
                  required
                />
                <CalculatorNumberInput
                  label="Height (inches)"
                  value={heightIn}
                  onChange={setHeightIn}
                  min={0}
                  max={11}
                  step={1}
                  unit="in"
                  required
                />
              </div>
              <CalculatorNumberInput
                label="Weight"
                value={weightLbs}
                onChange={setWeightLbs}
                min={66}
                max={660}
                step={0.1}
                unit="lbs"
                required
              />
            </TabsContent>
          </Tabs>
        </CardContent>
      </Card>

      {bmr !== null && (
        <CalculatorResult 
          title="Your Basal Metabolic Rate Result"
          onDownload={downloadReport}
        >
          <div className="space-y-4">
            <div className="flex flex-col items-center justify-center">
              <div className="text-center">
                <div className="text-4xl font-bold">
                  {bmr}
                  <span className="text-lg ml-1">calories/day</span>
                </div>
                <div className="text-sm text-muted-foreground mt-1">
                  Basal Metabolic Rate
                </div>
              </div>
            </div>
            
            <div className="mt-4">
              <h4 className="font-medium mb-2">Daily Calorie Needs Based on Activity Level</h4>
              <div className="text-sm space-y-2">
                <div className="grid grid-cols-2 border-b pb-1">
                  <div className="font-medium">Activity Level</div>
                  <div className="font-medium text-right">Calories/Day</div>
                </div>
                <div className="grid grid-cols-2 border-b pb-1">
                  <div>Sedentary</div>
                  <div className="text-right">{Math.round(bmr * 1.2)}</div>
                </div>
                <div className="grid grid-cols-2 border-b pb-1">
                  <div>Lightly active</div>
                  <div className="text-right">{Math.round(bmr * 1.375)}</div>
                </div>
                <div className="grid grid-cols-2 border-b pb-1">
                  <div>Moderately active</div>
                  <div className="text-right">{Math.round(bmr * 1.55)}</div>
                </div>
                <div className="grid grid-cols-2 border-b pb-1">
                  <div>Very active</div>
                  <div className="text-right">{Math.round(bmr * 1.725)}</div>
                </div>
                <div className="grid grid-cols-2 border-b pb-1">
                  <div>Extremely active</div>
                  <div className="text-right">{Math.round(bmr * 1.9)}</div>
                </div>
              </div>
              <div className="text-xs text-muted-foreground mt-1">
                <ul className="list-disc list-inside">
                  <li>Sedentary: Little or no exercise</li>
                  <li>Lightly active: Light exercise 1-3 days/week</li>
                  <li>Moderately active: Moderate exercise 3-5 days/week</li>
                  <li>Very active: Hard exercise 6-7 days/week</li>
                  <li>Extremely active: Very hard exercise & physical job</li>
                </ul>
              </div>
            </div>
            
            <div className="text-sm text-muted-foreground">
              <p className="font-medium">What is BMR?</p>
              <p className="mt-1">
                Basal Metabolic Rate is the number of calories your body needs to maintain basic physiological functions while at complete rest. This includes breathing, circulation, cell production, nutrient processing, and protein synthesis. BMR represents the minimum amount of energy needed to keep your body functioning.
              </p>
              
              <p className="mt-3 font-medium">About the Mifflin-St Jeor Formula:</p>
              <ul className="list-disc list-inside mt-1">
                <li>For men: BMR = 10 × weight(kg) + 6.25 × height(cm) - 5 × age(years) + 5</li>
                <li>For women: BMR = 10 × weight(kg) + 6.25 × height(cm) - 5 × age(years) - 161</li>
              </ul>
              
              <p className="mt-2">
                Note: This calculation provides an estimate. Individual metabolism can vary based on genetic factors, body composition, hormone function, and health status.
              </p>
            </div>
          </div>
        </CalculatorResult>
      )}
    </div>
  );
}
