
import { useState, useEffect } from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Label } from "@/components/ui/label";
import { CalculatorNumberInput } from "@/components/calculator/calculator-number-input";
import { CalculatorResult, ResultAlert } from "@/components/calculator/calculator-result";

export function BodyFatPercentageCalculator() {
  const [gender, setGender] = useState<"male" | "female">("male");
  const [heightCm, setHeightCm] = useState<number>(175);
  const [neckCm, setNeckCm] = useState<number>(38);
  const [waistCm, setWaistCm] = useState<number>(85);
  const [hipCm, setHipCm] = useState<number>(90);
  
  const [bodyFatPercentage, setBodyFatPercentage] = useState<number | null>(null);
  const [category, setCategory] = useState<string>("");

  useEffect(() => {
    calculateBodyFat();
  }, [gender, heightCm, neckCm, waistCm, hipCm]);

  const calculateBodyFat = () => {
    let bodyFatPercent: number;

    if (gender === "male") {
      // U.S. Navy formula for men
      bodyFatPercent = 495 / (1.0324 - 0.19077 * Math.log10(waistCm - neckCm) + 0.15456 * Math.log10(heightCm)) - 450;
    } else {
      // U.S. Navy formula for women
      bodyFatPercent = 495 / (1.29579 - 0.35004 * Math.log10(waistCm + hipCm - neckCm) + 0.22100 * Math.log10(heightCm)) - 450;
    }

    bodyFatPercent = parseFloat(bodyFatPercent.toFixed(1));
    setBodyFatPercentage(bodyFatPercent);

    // Set category based on gender and body fat percentage
    if (gender === "male") {
      if (bodyFatPercent < 6) setCategory("Essential fat");
      else if (bodyFatPercent >= 6 && bodyFatPercent < 14) setCategory("Athletic");
      else if (bodyFatPercent >= 14 && bodyFatPercent < 18) setCategory("Fitness");
      else if (bodyFatPercent >= 18 && bodyFatPercent < 25) setCategory("Average");
      else setCategory("Obese");
    } else {
      if (bodyFatPercent < 14) setCategory("Essential fat");
      else if (bodyFatPercent >= 14 && bodyFatPercent < 21) setCategory("Athletic");
      else if (bodyFatPercent >= 21 && bodyFatPercent < 25) setCategory("Fitness");
      else if (bodyFatPercent >= 25 && bodyFatPercent < 32) setCategory("Average");
      else setCategory("Obese");
    }
  };

  const getAlertType = () => {
    if (!bodyFatPercentage) return "info";
    
    if (gender === "male") {
      if (bodyFatPercentage < 6) return "warning";
      if (bodyFatPercentage >= 6 && bodyFatPercentage < 18) return "success";
      if (bodyFatPercentage >= 18 && bodyFatPercentage < 25) return "info";
      return "warning";
    } else {
      if (bodyFatPercentage < 14) return "warning";
      if (bodyFatPercentage >= 14 && bodyFatPercentage < 25) return "success";
      if (bodyFatPercentage >= 25 && bodyFatPercentage < 32) return "info";
      return "warning";
    }
  };

  const getCategoryDescription = () => {
    switch(category) {
      case "Essential fat":
        return "This is the minimum level of fat needed for basic physical and physiological health functions.";
      case "Athletic":
        return "This range is typical for athletes and those with very active lifestyles.";
      case "Fitness":
        return "This range indicates good fitness and is achievable with consistent exercise and healthy eating.";
      case "Average":
        return "This is typical for the general population. Small improvements to diet and exercise could be beneficial.";
      case "Obese":
        return "This level is associated with health risks. Consider consulting a healthcare professional for personalized advice.";
      default:
        return "";
    }
  };

  const downloadReport = () => {
    if (!bodyFatPercentage) return;
    
    const report = `
BODY FAT PERCENTAGE CALCULATION REPORT (Navy Method)
--------------------------------------------------
Date: ${new Date().toLocaleDateString()}

YOUR MEASUREMENTS:
Gender: ${gender === "male" ? "Male" : "Female"}
Height: ${heightCm} cm
Neck Circumference: ${neckCm} cm
Waist Circumference: ${waistCm} cm
${gender === "female" ? `Hip Circumference: ${hipCm} cm` : ""}

RESULTS:
Body Fat Percentage: ${bodyFatPercentage}%
Category: ${category}

INTERPRETATION:
${getCategoryDescription()}

BODY FAT PERCENTAGE CATEGORIES FOR ${gender === "male" ? "MEN" : "WOMEN"}:
${gender === "male" ? 
`- Essential fat: 2-5%
- Athletic: 6-13%
- Fitness: 14-17%
- Average: 18-24%
- Obese: 25% and higher` : 
`- Essential fat: 10-13%
- Athletic: 14-20%
- Fitness: 21-24%
- Average: 25-31%
- Obese: 32% and higher`}

Note: The U.S. Navy method provides an estimate of body fat percentage.
For more accurate results, consider professional body composition testing.

Generated by: Vital Metrics Health Calculator
`;

    const blob = new Blob([report], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `body-fat-report-${new Date().toLocaleDateString().replace(/\//g, '-')}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6">
      <Card>
        <CardHeader>
          <CardTitle>Body Fat Percentage Calculator (Navy Method)</CardTitle>
          <CardDescription>
            Calculate your body fat percentage using the U.S. Navy method, which estimates body fat based on neck, waist, and hip measurements.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="space-y-3">
            <Label>Gender</Label>
            <RadioGroup
              value={gender}
              onValueChange={(value) => setGender(value as "male" | "female")}
              className="flex space-x-4"
            >
              <div className="flex items-center space-x-2">
                <RadioGroupItem value="male" id="male" />
                <Label htmlFor="male">Male</Label>
              </div>
              <div className="flex items-center space-x-2">
                <RadioGroupItem value="female" id="female" />
                <Label htmlFor="female">Female</Label>
              </div>
            </RadioGroup>
          </div>

          <CalculatorNumberInput
            label="Height"
            value={heightCm}
            onChange={setHeightCm}
            min={120}
            max={250}
            unit="cm"
            required
          />

          <CalculatorNumberInput
            label="Neck Circumference"
            value={neckCm}
            onChange={setNeckCm}
            min={20}
            max={80}
            unit="cm"
            required
          />

          <CalculatorNumberInput
            label="Waist Circumference"
            value={waistCm}
            onChange={setWaistCm}
            min={40}
            max={200}
            unit="cm"
            description="Measure at the narrowest point"
            required
          />

          {gender === "female" && (
            <CalculatorNumberInput
              label="Hip Circumference"
              value={hipCm}
              onChange={setHipCm}
              min={60}
              max={200}
              unit="cm"
              description="Measure at the widest point"
              required
            />
          )}
        </CardContent>
      </Card>

      {bodyFatPercentage !== null && (
        <CalculatorResult 
          title="Your Body Fat Percentage Result"
          onDownload={downloadReport}
        >
          <div className="space-y-4">
            <div className="flex items-center justify-center">
              <div className="text-center">
                <div className="text-4xl font-bold">{bodyFatPercentage}%</div>
                <div className="text-sm text-muted-foreground mt-1">Body Fat Percentage</div>
              </div>
            </div>
            
            <ResultAlert type={getAlertType()} title={`Category: ${category}`}>
              {getCategoryDescription()}
            </ResultAlert>
            
            <div className="text-sm text-muted-foreground">
              <p>Body Fat Percentage Categories for {gender === "male" ? "Men" : "Women"}:</p>
              {gender === "male" ? (
                <ul className="list-disc list-inside mt-1">
                  <li>Essential fat: 2-5%</li>
                  <li>Athletic: 6-13%</li>
                  <li>Fitness: 14-17%</li>
                  <li>Average: 18-24%</li>
                  <li>Obese: 25% and higher</li>
                </ul>
              ) : (
                <ul className="list-disc list-inside mt-1">
                  <li>Essential fat: 10-13%</li>
                  <li>Athletic: 14-20%</li>
                  <li>Fitness: 21-24%</li>
                  <li>Average: 25-31%</li>
                  <li>Obese: 32% and higher</li>
                </ul>
              )}
              <p className="mt-2">
                Note: The U.S. Navy method provides an estimate of body fat percentage. For more accurate results, consider professional body composition testing.
              </p>
            </div>
          </div>
        </CalculatorResult>
      )}
    </div>
  );
}
