
import { useState, useEffect } from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { CalculatorNumberInput } from "@/components/calculator/calculator-number-input";
import { CalculatorResult } from "@/components/calculator/calculator-result";

export function BodySurfaceAreaCalculator() {
  const [system, setSystem] = useState<"metric" | "imperial">("metric");
  
  // Metric
  const [heightCm, setHeightCm] = useState<number>(175);
  const [weightKg, setWeightKg] = useState<number>(70);
  
  // Imperial
  const [heightFt, setHeightFt] = useState<number>(5);
  const [heightIn, setHeightIn] = useState<number>(9);
  const [weightLbs, setWeightLbs] = useState<number>(154);
  
  const [bsa, setBsa] = useState<number | null>(null);

  useEffect(() => {
    calculateBSA();
  }, [heightCm, weightKg, heightFt, heightIn, weightLbs, system]);

  const calculateBSA = () => {
    let height: number; // in cm
    let weight: number; // in kg
    
    if (system === "metric") {
      height = heightCm;
      weight = weightKg;
    } else {
      // Convert feet and inches to cm
      height = ((heightFt * 12) + heightIn) * 2.54;
      // Convert lbs to kg
      weight = weightLbs * 0.453592;
    }
    
    // DuBois Formula for BSA
    // BSA (m²) = 0.007184 × Height(cm)^0.725 × Weight(kg)^0.425
    const calculatedBSA = 0.007184 * Math.pow(height, 0.725) * Math.pow(weight, 0.425);
    setBsa(parseFloat(calculatedBSA.toFixed(2)));
  };

  const downloadReport = () => {
    if (!bsa) return;
    
    const height = system === "metric" 
      ? `${heightCm} cm` 
      : `${heightFt}'${heightIn}" (${((heightFt * 12) + heightIn) * 2.54} cm)`;
    
    const weight = system === "metric"
      ? `${weightKg} kg`
      : `${weightLbs} lbs (${(weightLbs * 0.453592).toFixed(1)} kg)`;
    
    const report = `
BODY SURFACE AREA CALCULATION REPORT (DuBois Formula)
----------------------------------------------------
Date: ${new Date().toLocaleDateString()}

YOUR MEASUREMENTS:
Height: ${height}
Weight: ${weight}

RESULTS:
Body Surface Area (BSA): ${bsa} m²

ABOUT THE CALCULATION:
The DuBois formula was used to calculate your body surface area:
BSA (m²) = 0.007184 × Height(cm)^0.725 × Weight(kg)^0.425

APPLICATIONS:
Body surface area is used to:
- Calculate drug dosages, especially for chemotherapy
- Determine cardiac output and other vital measurements
- Adjust fluid requirements in critical care
- Estimate burn areas for treatment

Note: Body surface area is primarily a clinical measurement used by healthcare professionals.
For most health assessments, other metrics like BMI may be more relevant for general use.

Generated by: Vital Metrics Health Calculator
`;

    const blob = new Blob([report], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `body-surface-area-report-${new Date().toLocaleDateString().replace(/\//g, '-')}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6">
      <Card>
        <CardHeader>
          <CardTitle>Body Surface Area Calculator (DuBois Formula)</CardTitle>
          <CardDescription>
            Calculate your body surface area (BSA) using the DuBois formula, commonly used in medical dosing and clinical assessments.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <Tabs value={system} onValueChange={(v) => setSystem(v as "metric" | "imperial")}>
            <TabsList className="grid w-full grid-cols-2">
              <TabsTrigger value="metric">Metric</TabsTrigger>
              <TabsTrigger value="imperial">Imperial</TabsTrigger>
            </TabsList>
            <TabsContent value="metric" className="space-y-4">
              <CalculatorNumberInput
                label="Height"
                value={heightCm}
                onChange={setHeightCm}
                min={50}
                max={250}
                step={1}
                unit="cm"
                required
              />
              <CalculatorNumberInput
                label="Weight"
                value={weightKg}
                onChange={setWeightKg}
                min={20}
                max={300}
                step={0.1}
                unit="kg"
                required
              />
            </TabsContent>
            <TabsContent value="imperial" className="space-y-4">
              <div className="grid grid-cols-2 gap-4">
                <CalculatorNumberInput
                  label="Height (feet)"
                  value={heightFt}
                  onChange={setHeightFt}
                  min={1}
                  max={8}
                  step={1}
                  unit="ft"
                  required
                />
                <CalculatorNumberInput
                  label="Height (inches)"
                  value={heightIn}
                  onChange={setHeightIn}
                  min={0}
                  max={11}
                  step={1}
                  unit="in"
                  required
                />
              </div>
              <CalculatorNumberInput
                label="Weight"
                value={weightLbs}
                onChange={setWeightLbs}
                min={44}
                max={660}
                step={0.1}
                unit="lbs"
                required
              />
            </TabsContent>
          </Tabs>
        </CardContent>
      </Card>

      {bsa !== null && (
        <CalculatorResult 
          title="Your Body Surface Area Result"
          onDownload={downloadReport}
        >
          <div className="space-y-4">
            <div className="flex flex-col items-center justify-center">
              <div className="text-center">
                <div className="text-4xl font-bold">
                  {bsa}
                  <span className="text-xl ml-1">m²</span>
                </div>
                <div className="text-sm text-muted-foreground mt-1">Body Surface Area</div>
              </div>
            </div>
            
            <div className="text-sm text-muted-foreground">
              <p className="font-medium">Applications of Body Surface Area:</p>
              <ul className="list-disc list-inside mt-1">
                <li>Calculation of drug dosages, especially for chemotherapy medications</li>
                <li>Determination of cardiac output and other vital measurements</li>
                <li>Adjustment of fluid requirements in critical care</li>
                <li>Estimation of burn areas for treatment</li>
              </ul>
              
              <p className="mt-3 font-medium">About the DuBois Formula:</p>
              <p className="mt-1">
                The DuBois formula used in this calculator is:
                <br />
                BSA (m²) = 0.007184 × Height(cm)<sup>0.725</sup> × Weight(kg)<sup>0.425</sup>
              </p>
              
              <p className="mt-2">
                Note: Body surface area is primarily a clinical measurement used by healthcare professionals. For most health assessments, other metrics like BMI may be more relevant for general use.
              </p>
            </div>
          </div>
        </CalculatorResult>
      )}
    </div>
  );
}
