
import { useState, useEffect } from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { CalculatorNumberInput } from "@/components/calculator/calculator-number-input";
import { CalculatorResult } from "@/components/calculator/calculator-result";

export function HeartRateZonesCalculator() {
  const [age, setAge] = useState<number>(30);
  const [heartRateZones, setHeartRateZones] = useState<{
    veryLight: string;
    light: string;
    moderate: string;
    hard: string;
    maximum: string;
  } | null>(null);

  useEffect(() => {
    calculateHeartRateZones();
  }, [age]);

  const calculateHeartRateZones = () => {
    // Maximum heart rate using the formula: 220 - age
    const maxHR = 220 - age;
    
    // Calculate heart rate zones
    // Zone 1 (Very Light): 50-60% of max
    const veryLightLow = Math.round(maxHR * 0.5);
    const veryLightHigh = Math.round(maxHR * 0.6);
    
    // Zone 2 (Light): 60-70% of max
    const lightLow = Math.round(maxHR * 0.6);
    const lightHigh = Math.round(maxHR * 0.7);
    
    // Zone 3 (Moderate): 70-80% of max
    const moderateLow = Math.round(maxHR * 0.7);
    const moderateHigh = Math.round(maxHR * 0.8);
    
    // Zone 4 (Hard): 80-90% of max
    const hardLow = Math.round(maxHR * 0.8);
    const hardHigh = Math.round(maxHR * 0.9);
    
    // Zone 5 (Maximum): 90-100% of max
    const maximumLow = Math.round(maxHR * 0.9);
    const maximumHigh = maxHR;
    
    setHeartRateZones({
      veryLight: `${veryLightLow}-${veryLightHigh}`,
      light: `${lightLow}-${lightHigh}`,
      moderate: `${moderateLow}-${moderateHigh}`,
      hard: `${hardLow}-${hardHigh}`,
      maximum: `${maximumLow}-${maximumHigh}`,
    });
  };

  const downloadReport = () => {
    if (!heartRateZones) return;
    
    const report = `
HEART RATE ZONES CALCULATION REPORT
-----------------------------------
Date: ${new Date().toLocaleDateString()}

YOUR INFORMATION:
Age: ${age} years

RESULTS:
Maximum Heart Rate: ${220 - age} bpm

HEART RATE ZONES:
Zone 1 - Very Light (50-60%): ${heartRateZones.veryLight} bpm
Zone 2 - Light (60-70%): ${heartRateZones.light} bpm
Zone 3 - Moderate (70-80%): ${heartRateZones.moderate} bpm
Zone 4 - Hard (80-90%): ${heartRateZones.hard} bpm
Zone 5 - Maximum (90-100%): ${heartRateZones.maximum} bpm

ZONE DESCRIPTIONS:
Zone 1 (Very Light): Perfect for warm-up and recovery. Helps improve general endurance.
Zone 2 (Light): Improves basic endurance and fat burning. Good for long, easy training sessions.
Zone 3 (Moderate): Improves aerobic fitness. Moderate intensity that feels somewhat hard.
Zone 4 (Hard): Improves anaerobic threshold. High intensity that feels challenging.
Zone 5 (Maximum): Improves maximum performance and speed. Very high intensity, can only be sustained for short periods.

Note: These heart rate zones are calculated using the simple formula (220 - age).
For more accurate heart rate zones, consider getting a professional assessment.

Generated by: Vital Metrics Health Calculator
`;

    const blob = new Blob([report], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `heart-rate-zones-report-${new Date().toLocaleDateString().replace(/\//g, '-')}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6">
      <Card>
        <CardHeader>
          <CardTitle>Heart Rate Zones Calculator</CardTitle>
          <CardDescription>
            Calculate your target heart rate zones based on your age using the 220-age formula. These zones help optimize your workouts for different fitness goals.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <CalculatorNumberInput
            label="Age"
            value={age}
            onChange={setAge}
            min={10}
            max={100}
            step={1}
            unit="years"
            required
          />
        </CardContent>
      </Card>

      {heartRateZones && (
        <CalculatorResult 
          title="Your Heart Rate Zones"
          onDownload={downloadReport}
        >
          <div className="space-y-4">
            <div className="text-center mb-4">
              <div className="text-4xl font-bold">{220 - age}</div>
              <div className="text-sm text-muted-foreground">Maximum Heart Rate (bpm)</div>
            </div>
            
            <div className="grid grid-cols-1 gap-3">
              <div className="p-3 bg-red-50 border border-red-100 rounded-lg">
                <div className="flex justify-between items-center">
                  <div>
                    <span className="font-semibold">Zone 5: Maximum</span>
                    <p className="text-xs text-muted-foreground">90-100% of max</p>
                  </div>
                  <div className="text-lg font-bold">{heartRateZones.maximum} <span className="text-sm">bpm</span></div>
                </div>
              </div>
              
              <div className="p-3 bg-orange-50 border border-orange-100 rounded-lg">
                <div className="flex justify-between items-center">
                  <div>
                    <span className="font-semibold">Zone 4: Hard</span>
                    <p className="text-xs text-muted-foreground">80-90% of max</p>
                  </div>
                  <div className="text-lg font-bold">{heartRateZones.hard} <span className="text-sm">bpm</span></div>
                </div>
              </div>
              
              <div className="p-3 bg-yellow-50 border border-yellow-100 rounded-lg">
                <div className="flex justify-between items-center">
                  <div>
                    <span className="font-semibold">Zone 3: Moderate</span>
                    <p className="text-xs text-muted-foreground">70-80% of max</p>
                  </div>
                  <div className="text-lg font-bold">{heartRateZones.moderate} <span className="text-sm">bpm</span></div>
                </div>
              </div>
              
              <div className="p-3 bg-green-50 border border-green-100 rounded-lg">
                <div className="flex justify-between items-center">
                  <div>
                    <span className="font-semibold">Zone 2: Light</span>
                    <p className="text-xs text-muted-foreground">60-70% of max</p>
                  </div>
                  <div className="text-lg font-bold">{heartRateZones.light} <span className="text-sm">bpm</span></div>
                </div>
              </div>
              
              <div className="p-3 bg-blue-50 border border-blue-100 rounded-lg">
                <div className="flex justify-between items-center">
                  <div>
                    <span className="font-semibold">Zone 1: Very Light</span>
                    <p className="text-xs text-muted-foreground">50-60% of max</p>
                  </div>
                  <div className="text-lg font-bold">{heartRateZones.veryLight} <span className="text-sm">bpm</span></div>
                </div>
              </div>
            </div>
            
            <div className="text-sm text-muted-foreground mt-4">
              <p className="font-medium">About Heart Rate Zones:</p>
              <ul className="list-disc list-inside mt-1 space-y-1">
                <li><span className="font-medium">Zone 1 (Very Light):</span> Perfect for warm-up and recovery. Helps improve general endurance.</li>
                <li><span className="font-medium">Zone 2 (Light):</span> Improves basic endurance and fat burning. Good for long, easy training sessions.</li>
                <li><span className="font-medium">Zone 3 (Moderate):</span> Improves aerobic fitness. Moderate intensity that feels somewhat hard.</li>
                <li><span className="font-medium">Zone 4 (Hard):</span> Improves anaerobic threshold. High intensity that feels challenging.</li>
                <li><span className="font-medium">Zone 5 (Maximum):</span> Improves maximum performance and speed. Very high intensity, can only be sustained for short periods.</li>
              </ul>
              
              <p className="mt-3">
                Note: These heart rate zones are calculated using the simple formula (220 - age). For more accurate heart rate zones, consider getting a professional assessment.
              </p>
            </div>
          </div>
        </CalculatorResult>
      )}
    </div>
  );
}
