import { useState, useEffect } from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { CalculatorNumberInput } from "@/components/calculator/calculator-number-input";
import { CalculatorResult } from "@/components/calculator/calculator-result";

export function HeartRateZonesCalculator() {
  const [age, setAge] = useState<number>(30);
  const [heartRateZones, setHeartRateZones] = useState<{
    veryLight: string;
    light: string;
    moderate: string;
    hard: string;
    maximum: string;
  } | null>(null);

  useEffect(() => {
    calculateHeartRateZones();
  }, [age]);

  const calculateHeartRateZones = () => {
    // Maximum heart rate using the formula: 220 - age
    const maxHR = 220 - age;
    
    // Calculate heart rate zones
    // Zone 1 (Very Light): 50-60% of max
    const veryLightLow = Math.round(maxHR * 0.5);
    const veryLightHigh = Math.round(maxHR * 0.6);
    
    // Zone 2 (Light): 60-70% of max
    const lightLow = Math.round(maxHR * 0.6);
    const lightHigh = Math.round(maxHR * 0.7);
    
    // Zone 3 (Moderate): 70-80% of max
    const moderateLow = Math.round(maxHR * 0.7);
    const moderateHigh = Math.round(maxHR * 0.8);
    
    // Zone 4 (Hard): 80-90% of max
    const hardLow = Math.round(maxHR * 0.8);
    const hardHigh = Math.round(maxHR * 0.9);
    
    // Zone 5 (Maximum): 90-100% of max
    const maximumLow = Math.round(maxHR * 0.9);
    const maximumHigh = maxHR;
    
    setHeartRateZones({
      veryLight: `${veryLightLow}-${veryLightHigh}`,
      light: `${lightLow}-${lightHigh}`,
      moderate: `${moderateLow}-${moderateHigh}`,
      hard: `${hardLow}-${hardHigh}`,
      maximum: `${maximumLow}-${maximumHigh}`,
    });
  };

  const downloadReport = () => {
    if (!heartRateZones) return;
    
    const report = `
HEART RATE ZONES CALCULATION REPORT
-----------------------------------
Date: ${new Date().toLocaleDateString()}

YOUR INFORMATION:
Age: ${age} years

RESULTS:
Maximum Heart Rate: ${220 - age} bpm

HEART RATE ZONES:
Zone 1 - Very Light (50-60%): ${heartRateZones.veryLight} bpm
Zone 2 - Light (60-70%): ${heartRateZones.light} bpm
Zone 3 - Moderate (70-80%): ${heartRateZones.moderate} bpm
Zone 4 - Hard (80-90%): ${heartRateZones.hard} bpm
Zone 5 - Maximum (90-100%): ${heartRateZones.maximum} bpm

ZONE DESCRIPTIONS:
Zone 1 (Very Light): Perfect for warm-up and recovery. Helps improve general endurance.
Zone 2 (Light): Improves basic endurance and fat burning. Good for long, easy training sessions.
Zone 3 (Moderate): Improves aerobic fitness. Moderate intensity that feels somewhat hard.
Zone 4 (Hard): Improves anaerobic threshold. High intensity that feels challenging.
Zone 5 (Maximum): Improves maximum performance and speed. Very high intensity, can only be sustained for short periods.

Note: These heart rate zones are calculated using the simple formula (220 - age).
For more accurate heart rate zones, consider getting a professional assessment.

Generated by: Vital Metrics Health Calculator
`;

    const blob = new Blob([report], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `heart-rate-zones-report-${new Date().toLocaleDateString().replace(/\//g, '-')}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6">
      <Card>
        <CardHeader>
          <CardTitle>Heart Rate Zones Calculator</CardTitle>
          <CardDescription>
            Calculate your target heart rate zones based on your age using the 220-age formula. These zones help optimize your workouts for different fitness goals.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <CalculatorNumberInput
            label="Age"
            value={age}
            onChange={setAge}
            min={10}
            max={100}
            step={1}
            unit="years"
            required
          />
        </CardContent>
      </Card>

      {heartRateZones && (
        <CalculatorResult 
          title="Your Heart Rate Zones"
          onDownload={downloadReport}
        >
          <div className="space-y-4">
            <div className="text-center mb-6">
              <div className="text-4xl font-bold text-slate-900 dark:text-white">{220 - age}</div>
              <div className="text-sm text-muted-foreground dark:text-slate-300">Maximum Heart Rate (bpm)</div>
            </div>
            
            <div className="grid grid-cols-1 gap-3">
              <div className="relative overflow-hidden p-4 bg-red-100 dark:bg-slate-900 border-2 border-red-500 dark:border-red-500 rounded-lg">
                <div className="absolute inset-0 bg-gradient-to-r from-red-500/10 to-red-600/10 dark:from-red-500/20 dark:to-red-600/20" />
                <div className="relative flex justify-between items-center">
                  <div className="space-y-1">
                    <span className="block font-bold text-lg text-red-900 dark:text-red-400">Zone 5: Maximum</span>
                    <div className="flex flex-col">
                      <span className="text-2xl font-bold text-red-900 dark:text-red-300">{heartRateZones.maximum}</span>
                      <span className="text-sm text-red-800 dark:text-red-400">90-100% of max</span>
                    </div>
                  </div>
                  <div className="text-sm font-medium text-red-900 dark:text-red-300">bpm</div>
                </div>
              </div>
              
              <div className="relative overflow-hidden p-4 bg-orange-100 dark:bg-slate-900 border-2 border-orange-500 dark:border-orange-500 rounded-lg">
                <div className="absolute inset-0 bg-gradient-to-r from-orange-500/10 to-orange-600/10 dark:from-orange-500/20 dark:to-orange-600/20" />
                <div className="relative flex justify-between items-center">
                  <div className="space-y-1">
                    <span className="block font-bold text-lg text-orange-900 dark:text-orange-400">Zone 4: Hard</span>
                    <div className="flex flex-col">
                      <span className="text-2xl font-bold text-orange-900 dark:text-orange-300">{heartRateZones.hard}</span>
                      <span className="text-sm text-orange-800 dark:text-orange-400">80-90% of max</span>
                    </div>
                  </div>
                  <div className="text-sm font-medium text-orange-900 dark:text-orange-300">bpm</div>
                </div>
              </div>
              
              <div className="relative overflow-hidden p-4 bg-yellow-100 dark:bg-slate-900 border-2 border-yellow-500 dark:border-yellow-500 rounded-lg">
                <div className="absolute inset-0 bg-gradient-to-r from-yellow-500/10 to-yellow-600/10 dark:from-yellow-500/20 dark:to-yellow-600/20" />
                <div className="relative flex justify-between items-center">
                  <div className="space-y-1">
                    <span className="block font-bold text-lg text-yellow-900 dark:text-yellow-400">Zone 3: Moderate</span>
                    <div className="flex flex-col">
                      <span className="text-2xl font-bold text-yellow-900 dark:text-yellow-300">{heartRateZones.moderate}</span>
                      <span className="text-sm text-yellow-800 dark:text-yellow-400">70-80% of max</span>
                    </div>
                  </div>
                  <div className="text-sm font-medium text-yellow-900 dark:text-yellow-300">bpm</div>
                </div>
              </div>
              
              <div className="relative overflow-hidden p-4 bg-green-100 dark:bg-slate-900 border-2 border-green-500 dark:border-green-500 rounded-lg">
                <div className="absolute inset-0 bg-gradient-to-r from-green-500/10 to-green-600/10 dark:from-green-500/20 dark:to-green-600/20" />
                <div className="relative flex justify-between items-center">
                  <div className="space-y-1">
                    <span className="block font-bold text-lg text-green-900 dark:text-green-400">Zone 2: Light</span>
                    <div className="flex flex-col">
                      <span className="text-2xl font-bold text-green-900 dark:text-green-300">{heartRateZones.light}</span>
                      <span className="text-sm text-green-800 dark:text-green-400">60-70% of max</span>
                    </div>
                  </div>
                  <div className="text-sm font-medium text-green-900 dark:text-green-300">bpm</div>
                </div>
              </div>
              
              <div className="relative overflow-hidden p-4 bg-blue-100 dark:bg-slate-900 border-2 border-blue-500 dark:border-blue-500 rounded-lg">
                <div className="absolute inset-0 bg-gradient-to-r from-blue-500/10 to-blue-600/10 dark:from-blue-500/20 dark:to-blue-600/20" />
                <div className="relative flex justify-between items-center">
                  <div className="space-y-1">
                    <span className="block font-bold text-lg text-blue-900 dark:text-blue-400">Zone 1: Very Light</span>
                    <div className="flex flex-col">
                      <span className="text-2xl font-bold text-blue-900 dark:text-blue-300">{heartRateZones.veryLight}</span>
                      <span className="text-sm text-blue-800 dark:text-blue-400">50-60% of max</span>
                    </div>
                  </div>
                  <div className="text-sm font-medium text-blue-900 dark:text-blue-300">bpm</div>
                </div>
              </div>
            </div>
            
            <div className="text-sm text-slate-600 dark:text-slate-300 mt-6">
              <p className="font-medium text-slate-800 dark:text-white">About Heart Rate Zones:</p>
              <ul className="list-disc list-inside mt-2 space-y-2">
                <li><span className="font-medium text-blue-600 dark:text-blue-400">Zone 1 (Very Light):</span> Perfect for warm-up and recovery. Helps improve general endurance.</li>
                <li><span className="font-medium text-green-600 dark:text-green-400">Zone 2 (Light):</span> Improves basic endurance and fat burning. Good for long, easy training sessions.</li>
                <li><span className="font-medium text-yellow-600 dark:text-yellow-400">Zone 3 (Moderate):</span> Improves aerobic fitness. Moderate intensity that feels somewhat hard.</li>
                <li><span className="font-medium text-orange-600 dark:text-orange-400">Zone 4 (Hard):</span> Improves anaerobic threshold. High intensity that feels challenging.</li>
                <li><span className="font-medium text-red-600 dark:text-red-400">Zone 5 (Maximum):</span> Improves maximum performance and speed. Very high intensity, can only be sustained for short periods.</li>
              </ul>
              
              <p className="mt-4 text-slate-600 dark:text-slate-300">
                Note: These heart rate zones are calculated using the simple formula (220 - age). For more accurate heart rate zones, consider getting a professional assessment.
              </p>
            </div>
          </div>
        </CalculatorResult>
      )}
    </div>
  );
}
