
import { useState, useEffect } from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Label } from "@/components/ui/label";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { CalculatorNumberInput } from "@/components/calculator/calculator-number-input";
import { CalculatorResult } from "@/components/calculator/calculator-result";

export function IdealBodyWeightCalculator() {
  const [gender, setGender] = useState<"male" | "female">("male");
  const [system, setSystem] = useState<"metric" | "imperial">("metric");
  
  // Metric
  const [heightCm, setHeightCm] = useState<number>(175);
  
  // Imperial
  const [heightFt, setHeightFt] = useState<number>(5);
  const [heightIn, setHeightIn] = useState<number>(9);
  
  const [idealWeight, setIdealWeight] = useState<number | null>(null);
  const [idealWeightRange, setIdealWeightRange] = useState<[number, number] | null>(null);

  useEffect(() => {
    calculateIdealWeight();
  }, [gender, heightCm, heightFt, heightIn, system]);

  const calculateIdealWeight = () => {
    let height: number;
    
    if (system === "metric") {
      // Convert cm to inches for calculation
      height = heightCm / 2.54;
    } else {
      // Convert feet and inches to inches
      height = (heightFt * 12) + heightIn;
    }
    
    // Devine formula
    let weight: number;
    if (gender === "male") {
      weight = 50 + (0.91 * (height - 60));
    } else {
      weight = 45.5 + (0.91 * (height - 60));
    }
    
    // Convert to kg if metric
    let calculatedWeight = system === "metric" ? weight : weight * 0.453592;
    calculatedWeight = parseFloat(calculatedWeight.toFixed(1));
    setIdealWeight(calculatedWeight);
    
    // Calculate range (±10%)
    const lowerRange = parseFloat((calculatedWeight * 0.9).toFixed(1));
    const upperRange = parseFloat((calculatedWeight * 1.1).toFixed(1));
    setIdealWeightRange([lowerRange, upperRange]);
  };

  const downloadReport = () => {
    if (!idealWeight || !idealWeightRange) return;
    
    const height = system === "metric" 
      ? `${heightCm} cm` 
      : `${heightFt}'${heightIn}"`;
    
    const weightUnit = system === "metric" ? "kg" : "lbs";
    const displayWeight = system === "metric" 
      ? idealWeight 
      : parseFloat((idealWeight / 0.453592).toFixed(1));
    
    const displayWeightRange = system === "metric"
      ? `${idealWeightRange[0]} - ${idealWeightRange[1]} kg`
      : `${parseFloat((idealWeightRange[0] / 0.453592).toFixed(1))} - ${parseFloat((idealWeightRange[1] / 0.453592).toFixed(1))} lbs`;
    
    const report = `
IDEAL BODY WEIGHT CALCULATION REPORT (Devine Formula)
----------------------------------------------------
Date: ${new Date().toLocaleDateString()}

YOUR INFORMATION:
Gender: ${gender === "male" ? "Male" : "Female"}
Height: ${height}

RESULTS:
Ideal Body Weight: ${displayWeight} ${weightUnit}
Healthy Weight Range (±10%): ${displayWeightRange}

ABOUT THE DEVINE FORMULA:
For men: IBW (kg) = 50 + 0.91 × (height in inches - 60)
For women: IBW (kg) = 45.5 + 0.91 × (height in inches - 60)

Note: This formula was developed for estimating drug dosages and provides a general guideline.
The ideal weight for an individual depends on many factors including frame size, muscle mass,
and overall health status.

Generated by: Vital Metrics Health Calculator
`;

    const blob = new Blob([report], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `ideal-body-weight-report-${new Date().toLocaleDateString().replace(/\//g, '-')}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6">
      <Card>
        <CardHeader>
          <CardTitle>Ideal Body Weight Calculator (Devine Formula)</CardTitle>
          <CardDescription>
            Calculate your ideal body weight based on height and gender using the Devine formula, commonly used in medical settings.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="space-y-3">
            <Label>Gender</Label>
            <RadioGroup
              value={gender}
              onValueChange={(value) => setGender(value as "male" | "female")}
              className="flex space-x-4"
            >
              <div className="flex items-center space-x-2">
                <RadioGroupItem value="male" id="male" />
                <Label htmlFor="male">Male</Label>
              </div>
              <div className="flex items-center space-x-2">
                <RadioGroupItem value="female" id="female" />
                <Label htmlFor="female">Female</Label>
              </div>
            </RadioGroup>
          </div>

          <Tabs value={system} onValueChange={(v) => setSystem(v as "metric" | "imperial")}>
            <TabsList className="grid w-full grid-cols-2">
              <TabsTrigger value="metric">Metric</TabsTrigger>
              <TabsTrigger value="imperial">Imperial</TabsTrigger>
            </TabsList>
            <TabsContent value="metric" className="space-y-4">
              <CalculatorNumberInput
                label="Height"
                value={heightCm}
                onChange={setHeightCm}
                min={120}
                max={250}
                unit="cm"
                required
              />
            </TabsContent>
            <TabsContent value="imperial" className="space-y-4">
              <div className="grid grid-cols-2 gap-4">
                <CalculatorNumberInput
                  label="Height (feet)"
                  value={heightFt}
                  onChange={setHeightFt}
                  min={3}
                  max={8}
                  unit="ft"
                  required
                />
                <CalculatorNumberInput
                  label="Height (inches)"
                  value={heightIn}
                  onChange={setHeightIn}
                  min={0}
                  max={11}
                  unit="in"
                  required
                />
              </div>
            </TabsContent>
          </Tabs>
        </CardContent>
      </Card>

      {idealWeight !== null && idealWeightRange !== null && (
        <CalculatorResult 
          title="Your Ideal Body Weight Result"
          onDownload={downloadReport}
        >
          <div className="space-y-4">
            <div className="flex flex-col items-center justify-center">
              <div className="text-center">
                <div className="text-4xl font-bold">
                  {system === "metric" ? idealWeight : parseFloat((idealWeight / 0.453592).toFixed(1))}
                  <span className="text-xl ml-1">{system === "metric" ? "kg" : "lbs"}</span>
                </div>
                <div className="text-sm text-muted-foreground mt-1">Ideal Body Weight</div>
              </div>
              
              <div className="mt-2 text-center">
                <div className="text-xl font-medium">
                  {system === "metric" 
                    ? `${idealWeightRange[0]} - ${idealWeightRange[1]} kg`
                    : `${parseFloat((idealWeightRange[0] / 0.453592).toFixed(1))} - ${parseFloat((idealWeightRange[1] / 0.453592).toFixed(1))} lbs`}
                </div>
                <div className="text-sm text-muted-foreground">Healthy Weight Range (±10%)</div>
              </div>
            </div>
            
            <div className="text-sm text-muted-foreground">
              <p>About the Devine Formula:</p>
              <ul className="list-disc list-inside mt-1">
                <li>For men: IBW (kg) = 50 + 0.91 × (height in inches - 60)</li>
                <li>For women: IBW (kg) = 45.5 + 0.91 × (height in inches - 60)</li>
              </ul>
              <p className="mt-2">
                Note: This formula was developed for estimating drug dosages and provides a general guideline. The ideal weight for an individual depends on many factors including frame size, muscle mass, and overall health status.
              </p>
            </div>
          </div>
        </CalculatorResult>
      )}
    </div>
  );
}
