
import { useState, useEffect } from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Label } from "@/components/ui/label";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { CalculatorNumberInput } from "@/components/calculator/calculator-number-input";
import { CalculatorResult } from "@/components/calculator/calculator-result";

export function LeanBodyMassCalculator() {
  const [gender, setGender] = useState<"male" | "female">("male");
  const [system, setSystem] = useState<"metric" | "imperial">("metric");
  
  // Metric
  const [heightCm, setHeightCm] = useState<number>(175);
  const [weightKg, setWeightKg] = useState<number>(70);
  
  // Imperial
  const [heightFt, setHeightFt] = useState<number>(5);
  const [heightIn, setHeightIn] = useState<number>(9);
  const [weightLbs, setWeightLbs] = useState<number>(154);
  
  const [lbm, setLbm] = useState<number | null>(null);
  const [lbmPercentage, setLbmPercentage] = useState<number | null>(null);
  const [fatMass, setFatMass] = useState<number | null>(null);

  useEffect(() => {
    calculateLBM();
  }, [gender, heightCm, weightKg, heightFt, heightIn, weightLbs, system]);

  const calculateLBM = () => {
    let height: number; // in cm
    let weight: number; // in kg
    
    if (system === "metric") {
      height = heightCm;
      weight = weightKg;
    } else {
      // Convert feet and inches to cm
      height = ((heightFt * 12) + heightIn) * 2.54;
      // Convert lbs to kg
      weight = weightLbs * 0.453592;
    }
    
    // Boer Formula for LBM
    let calculatedLBM: number;
    if (gender === "male") {
      // For men: LBM = 0.407 × weight(kg) + 0.267 × height(cm) - 19.2
      calculatedLBM = 0.407 * weight + 0.267 * height - 19.2;
    } else {
      // For women: LBM = 0.252 × weight(kg) + 0.473 × height(cm) - 48.3
      calculatedLBM = 0.252 * weight + 0.473 * height - 48.3;
    }
    
    calculatedLBM = parseFloat(calculatedLBM.toFixed(1));
    setLbm(calculatedLBM);
    
    // Calculate LBM percentage
    const lbmPct = (calculatedLBM / weight) * 100;
    setLbmPercentage(parseFloat(lbmPct.toFixed(1)));
    
    // Calculate fat mass
    const fatMass = weight - calculatedLBM;
    setFatMass(parseFloat(fatMass.toFixed(1)));
  };

  const displayValue = (value: number | null) => {
    if (value === null) return '';
    
    if (system === "metric") {
      return value;
    } else {
      // Convert kg to lbs
      return parseFloat((value / 0.453592).toFixed(1));
    }
  };

  const displayUnit = () => system === "metric" ? "kg" : "lbs";

  const downloadReport = () => {
    if (!lbm || !lbmPercentage || !fatMass) return;
    
    const height = system === "metric" 
      ? `${heightCm} cm` 
      : `${heightFt}'${heightIn}" (${((heightFt * 12) + heightIn) * 2.54} cm)`;
    
    const weight = system === "metric"
      ? `${weightKg} kg`
      : `${weightLbs} lbs (${(weightLbs * 0.453592).toFixed(1)} kg)`;
    
    const report = `
LEAN BODY MASS CALCULATION REPORT (Boer Formula)
------------------------------------------------
Date: ${new Date().toLocaleDateString()}

YOUR INFORMATION:
Gender: ${gender === "male" ? "Male" : "Female"}
Height: ${height}
Weight: ${weight}

RESULTS:
Lean Body Mass: ${lbm} kg ${system === "imperial" ? `(${displayValue(lbm)} lbs)` : ''}
Lean Body Mass Percentage: ${lbmPercentage}%
Fat Mass: ${fatMass} kg ${system === "imperial" ? `(${displayValue(fatMass)} lbs)` : ''}

ABOUT THE BOER FORMULA:
For men: LBM = 0.407 × weight(kg) + 0.267 × height(cm) - 19.2
For women: LBM = 0.252 × weight(kg) + 0.473 × height(cm) - 48.3

WHAT IS LEAN BODY MASS?
Lean body mass is the weight of your body excluding fat. It includes the weight of organs,
bones, muscles, blood, and skin. LBM is an important measure for various health assessments
including basal metabolic rate and medication dosing.

Note: The Boer formula provides an estimate of lean body mass. For more accurate body composition
measurements, consider methods like DEXA scans, bioelectrical impedance analysis, or hydrostatic weighing.

Generated by: Vital Metrics Health Calculator
`;

    const blob = new Blob([report], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `lean-body-mass-report-${new Date().toLocaleDateString().replace(/\//g, '-')}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6">
      <Card>
        <CardHeader>
          <CardTitle>Lean Body Mass Calculator (Boer Formula)</CardTitle>
          <CardDescription>
            Calculate your lean body mass (LBM) using the Boer formula, which estimates the weight of everything in your body except fat.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="space-y-3">
            <Label>Gender</Label>
            <RadioGroup
              value={gender}
              onValueChange={(value) => setGender(value as "male" | "female")}
              className="flex space-x-4"
            >
              <div className="flex items-center space-x-2">
                <RadioGroupItem value="male" id="lbm-male" />
                <Label htmlFor="lbm-male">Male</Label>
              </div>
              <div className="flex items-center space-x-2">
                <RadioGroupItem value="female" id="lbm-female" />
                <Label htmlFor="lbm-female">Female</Label>
              </div>
            </RadioGroup>
          </div>

          <Tabs value={system} onValueChange={(v) => setSystem(v as "metric" | "imperial")}>
            <TabsList className="grid w-full grid-cols-2">
              <TabsTrigger value="metric">Metric</TabsTrigger>
              <TabsTrigger value="imperial">Imperial</TabsTrigger>
            </TabsList>
            <TabsContent value="metric" className="space-y-4">
              <CalculatorNumberInput
                label="Height"
                value={heightCm}
                onChange={setHeightCm}
                min={120}
                max={250}
                step={1}
                unit="cm"
                required
              />
              <CalculatorNumberInput
                label="Weight"
                value={weightKg}
                onChange={setWeightKg}
                min={30}
                max={300}
                step={0.1}
                unit="kg"
                required
              />
            </TabsContent>
            <TabsContent value="imperial" className="space-y-4">
              <div className="grid grid-cols-2 gap-4">
                <CalculatorNumberInput
                  label="Height (feet)"
                  value={heightFt}
                  onChange={setHeightFt}
                  min={3}
                  max={8}
                  step={1}
                  unit="ft"
                  required
                />
                <CalculatorNumberInput
                  label="Height (inches)"
                  value={heightIn}
                  onChange={setHeightIn}
                  min={0}
                  max={11}
                  step={1}
                  unit="in"
                  required
                />
              </div>
              <CalculatorNumberInput
                label="Weight"
                value={weightLbs}
                onChange={setWeightLbs}
                min={66}
                max={660}
                step={0.1}
                unit="lbs"
                required
              />
            </TabsContent>
          </Tabs>
        </CardContent>
      </Card>

      {lbm !== null && lbmPercentage !== null && fatMass !== null && (
        <CalculatorResult 
          title="Your Lean Body Mass Result"
          onDownload={downloadReport}
        >
          <div className="space-y-4">
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4 text-center">
              <div className="p-4 border rounded-lg">
                <div className="text-3xl font-bold">
                  {displayValue(lbm)}
                  <span className="text-lg ml-1">{displayUnit()}</span>
                </div>
                <div className="text-sm text-muted-foreground mt-1">Lean Body Mass</div>
              </div>
              
              <div className="p-4 border rounded-lg">
                <div className="text-3xl font-bold">
                  {lbmPercentage}
                  <span className="text-lg ml-1">%</span>
                </div>
                <div className="text-sm text-muted-foreground mt-1">LBM Percentage</div>
              </div>
              
              <div className="p-4 border rounded-lg">
                <div className="text-3xl font-bold">
                  {displayValue(fatMass)}
                  <span className="text-lg ml-1">{displayUnit()}</span>
                </div>
                <div className="text-sm text-muted-foreground mt-1">Fat Mass</div>
              </div>
            </div>
            
            <div className="text-sm text-muted-foreground">
              <p className="font-medium">What is Lean Body Mass?</p>
              <p className="mt-1">
                Lean body mass is the weight of your body excluding fat. It includes the weight of organs, bones, muscles, blood, and skin. LBM is an important measure for various health assessments including basal metabolic rate and medication dosing.
              </p>
              
              <p className="mt-3 font-medium">About the Boer Formula:</p>
              <ul className="list-disc list-inside mt-1">
                <li>For men: LBM = 0.407 × weight(kg) + 0.267 × height(cm) - 19.2</li>
                <li>For women: LBM = 0.252 × weight(kg) + 0.473 × height(cm) - 48.3</li>
              </ul>
              
              <p className="mt-2">
                Note: The Boer formula provides an estimate of lean body mass. For more accurate body composition measurements, consider methods like DEXA scans, bioelectrical impedance analysis, or hydrostatic weighing.
              </p>
            </div>
          </div>
        </CalculatorResult>
      )}
    </div>
  );
}
