
import { useState, useEffect } from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Label } from "@/components/ui/label";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { CalculatorNumberInput } from "@/components/calculator/calculator-number-input";
import { CalculatorResult, ResultAlert } from "@/components/calculator/calculator-result";

export function WaistToHipRatioCalculator() {
  const [gender, setGender] = useState<"male" | "female">("male");
  const [system, setSystem] = useState<"metric" | "imperial">("metric");
  
  // Metric
  const [waistCm, setWaistCm] = useState<number>(80);
  const [hipCm, setHipCm] = useState<number>(100);
  
  // Imperial
  const [waistIn, setWaistIn] = useState<number>(31.5);
  const [hipIn, setHipIn] = useState<number>(39.4);
  
  const [ratio, setRatio] = useState<number | null>(null);
  const [category, setCategory] = useState<string>("");

  useEffect(() => {
    calculateWHR();
  }, [gender, waistCm, hipCm, waistIn, hipIn, system]);

  const calculateWHR = () => {
    let waist: number;
    let hip: number;
    
    if (system === "metric") {
      waist = waistCm;
      hip = hipCm;
    } else {
      waist = waistIn;
      hip = hipIn;
    }
    
    if (waist > 0 && hip > 0) {
      const calculatedRatio = waist / hip;
      setRatio(parseFloat(calculatedRatio.toFixed(2)));
      
      // Determine health category based on gender and ratio
      setCategory(determineCategory(calculatedRatio, gender));
    }
  };

  const determineCategory = (ratio: number, gender: string): string => {
    if (gender === "male") {
      if (ratio < 0.9) return "Low Risk";
      if (ratio >= 0.9 && ratio < 1.0) return "Moderate Risk";
      return "High Risk";
    } else {
      if (ratio < 0.8) return "Low Risk";
      if (ratio >= 0.8 && ratio < 0.85) return "Moderate Risk";
      return "High Risk";
    }
  };

  const getCategoryColor = (): string => {
    switch (category) {
      case "Low Risk": return "text-green-600";
      case "Moderate Risk": return "text-yellow-600";
      case "High Risk": return "text-red-600";
      default: return "";
    }
  };

  const downloadReport = () => {
    if (ratio === null) return;
    
    const waistMeasurement = system === "metric" 
      ? `${waistCm} cm` 
      : `${waistIn} inches`;
    
    const hipMeasurement = system === "metric"
      ? `${hipCm} cm`
      : `${hipIn} inches`;
    
    const report = `
WAIST-TO-HIP RATIO REPORT
-------------------------
Date: ${new Date().toLocaleDateString()}

YOUR INFORMATION:
Gender: ${gender === "male" ? "Male" : "Female"}
Waist Circumference: ${waistMeasurement}
Hip Circumference: ${hipMeasurement}

RESULTS:
Waist-to-Hip Ratio: ${ratio}
Health Risk Category: ${category}

INTERPRETATION:
${gender === "male" 
  ? "For men, a WHR below 0.9 indicates low risk, 0.9-1.0 moderate risk, and above 1.0 high risk."
  : "For women, a WHR below 0.8 indicates low risk, 0.8-0.85 moderate risk, and above 0.85 high risk."
}

WHAT THIS MEANS:
The waist-to-hip ratio is a measure of body fat distribution. A higher ratio indicates more fat stored around the waist, which is associated with a higher risk of certain health conditions like heart disease, type 2 diabetes, and overall mortality.

RECOMMENDATIONS:
- Low Risk: Maintain your current lifestyle with balanced diet and regular exercise.
- Moderate Risk: Consider increasing physical activity and making dietary improvements.
- High Risk: Consult with a healthcare provider about strategies to reduce abdominal fat.

Note: This calculator provides an estimate and should not replace professional medical advice.

Generated by: Health Calculator App
`;

    const blob = new Blob([report], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `waist-to-hip-ratio-report-${new Date().toLocaleDateString().replace(/\//g, '-')}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6">
      <Card>
        <CardHeader>
          <CardTitle>Waist-to-Hip Ratio Calculator</CardTitle>
          <CardDescription>
            Calculate your waist-to-hip ratio (WHR), a measure of body fat distribution and health risk.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="space-y-3">
            <Label>Gender</Label>
            <RadioGroup
              value={gender}
              onValueChange={(value) => setGender(value as "male" | "female")}
              className="flex space-x-4"
            >
              <div className="flex items-center space-x-2">
                <RadioGroupItem value="male" id="whr-male" />
                <Label htmlFor="whr-male">Male</Label>
              </div>
              <div className="flex items-center space-x-2">
                <RadioGroupItem value="female" id="whr-female" />
                <Label htmlFor="whr-female">Female</Label>
              </div>
            </RadioGroup>
          </div>

          <Tabs value={system} onValueChange={(v) => setSystem(v as "metric" | "imperial")}>
            <TabsList className="grid w-full grid-cols-2">
              <TabsTrigger value="metric">Metric</TabsTrigger>
              <TabsTrigger value="imperial">Imperial</TabsTrigger>
            </TabsList>
            <TabsContent value="metric" className="space-y-4">
              <CalculatorNumberInput
                label="Waist Circumference"
                value={waistCm}
                onChange={setWaistCm}
                min={50}
                max={200}
                step={0.1}
                unit="cm"
                description="Measure at navel level"
                required
              />
              <CalculatorNumberInput
                label="Hip Circumference"
                value={hipCm}
                onChange={setHipCm}
                min={50}
                max={200}
                step={0.1}
                unit="cm"
                description="Measure at widest part"
                required
              />
            </TabsContent>
            <TabsContent value="imperial" className="space-y-4">
              <CalculatorNumberInput
                label="Waist Circumference"
                value={waistIn}
                onChange={setWaistIn}
                min={20}
                max={80}
                step={0.1}
                unit="inches"
                description="Measure at navel level"
                required
              />
              <CalculatorNumberInput
                label="Hip Circumference"
                value={hipIn}
                onChange={setHipIn}
                min={20}
                max={80}
                step={0.1}
                unit="inches"
                description="Measure at widest part"
                required
              />
            </TabsContent>
          </Tabs>
        </CardContent>
      </Card>

      {ratio !== null && (
        <CalculatorResult 
          title="Your Waist-to-Hip Ratio Result"
          onDownload={downloadReport}
        >
          <div className="space-y-4">
            <div className="flex flex-col items-center justify-center">
              <div className="text-center">
                <div className="text-4xl font-bold">{ratio}</div>
                <div className="text-sm text-muted-foreground mt-1">Waist-to-Hip Ratio</div>
              </div>
              
              <div className="mt-2 text-center">
                <div className={`text-xl font-medium ${getCategoryColor()}`}>
                  {category}
                </div>
                <div className="text-sm text-muted-foreground">Health Risk Category</div>
              </div>
            </div>
            
            <ResultAlert type={
              category === "Low Risk" ? "success" : 
              category === "Moderate Risk" ? "warning" : "error"
            } title={`Health Risk: ${category}`}>
              <p>
                {gender === "male" 
                  ? "For men, a WHR below 0.9 indicates low risk, 0.9-1.0 moderate risk, and above 1.0 high risk."
                  : "For women, a WHR below 0.8 indicates low risk, 0.8-0.85 moderate risk, and above 0.85 high risk."
                }
              </p>
            </ResultAlert>
            
            <div className="text-sm text-muted-foreground">
              <p className="font-medium">What this means:</p>
              <p className="mt-1">
                The waist-to-hip ratio is a measure of body fat distribution. A higher ratio indicates more fat stored around the waist, which is associated with a higher risk of certain health conditions like heart disease, type 2 diabetes, and overall mortality.
              </p>
              
              <p className="mt-3 font-medium">Recommendations:</p>
              <ul className="list-disc list-inside mt-1">
                <li><span className="font-medium">Low Risk:</span> Maintain your current lifestyle with balanced diet and regular exercise.</li>
                <li><span className="font-medium">Moderate Risk:</span> Consider increasing physical activity and making dietary improvements.</li>
                <li><span className="font-medium">High Risk:</span> Consult with a healthcare provider about strategies to reduce abdominal fat.</li>
              </ul>
            </div>
          </div>
        </CalculatorResult>
      )}
    </div>
  );
}
