
import { useState, useEffect } from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { CalculatorNumberInput } from "@/components/calculator/calculator-number-input";
import { CalculatorResult, ResultAlert } from "@/components/calculator/calculator-result";

export function WaistToHeightRatioCalculator() {
  const [system, setSystem] = useState<"metric" | "imperial">("metric");
  
  // Metric
  const [waistCm, setWaistCm] = useState<number>(80);
  const [heightCm, setHeightCm] = useState<number>(170);
  
  // Imperial
  const [waistIn, setWaistIn] = useState<number>(31.5);
  const [heightFt, setHeightFt] = useState<number>(5);
  const [heightIn, setHeightIn] = useState<number>(7);
  
  const [ratio, setRatio] = useState<number | null>(null);
  const [category, setCategory] = useState<string>("");

  useEffect(() => {
    calculateWHTR();
  }, [waistCm, heightCm, waistIn, heightFt, heightIn, system]);

  const calculateWHTR = () => {
    let waist: number;
    let height: number;
    
    if (system === "metric") {
      waist = waistCm;
      height = heightCm;
    } else {
      waist = waistIn;
      // Convert feet and inches to total inches
      height = ((heightFt * 12) + heightIn);
    }
    
    if (waist > 0 && height > 0) {
      const calculatedRatio = waist / height;
      setRatio(parseFloat(calculatedRatio.toFixed(2)));
      
      // Determine health category based on ratio
      setCategory(determineCategory(calculatedRatio));
    }
  };

  const determineCategory = (ratio: number): string => {
    if (ratio < 0.4) return "Underweight";
    if (ratio >= 0.4 && ratio < 0.5) return "Healthy";
    if (ratio >= 0.5 && ratio < 0.6) return "Overweight";
    return "Obese";
  };

  const getCategoryColor = (): string => {
    switch (category) {
      case "Underweight": return "text-blue-600";
      case "Healthy": return "text-green-600";
      case "Overweight": return "text-yellow-600";
      case "Obese": return "text-red-600";
      default: return "";
    }
  };

  const downloadReport = () => {
    if (ratio === null) return;
    
    const waistMeasurement = system === "metric" 
      ? `${waistCm} cm` 
      : `${waistIn} inches`;
    
    const heightMeasurement = system === "metric"
      ? `${heightCm} cm`
      : `${heightFt}'${heightIn}"`;
    
    const report = `
WAIST-TO-HEIGHT RATIO REPORT
---------------------------
Date: ${new Date().toLocaleDateString()}

YOUR INFORMATION:
Waist Circumference: ${waistMeasurement}
Height: ${heightMeasurement}

RESULTS:
Waist-to-Height Ratio: ${ratio}
Health Category: ${category}

INTERPRETATION:
- Below 0.4: Underweight
- 0.4 to 0.49: Healthy
- 0.5 to 0.59: Overweight
- 0.6 and above: Obese

WHAT THIS MEANS:
The waist-to-height ratio is a simple measurement for assessing health risk based on central obesity. Studies suggest it may be a better predictor of health risks than BMI.

GENERAL GUIDELINE:
"Keep your waist circumference to less than half your height."

RECOMMENDATIONS:
- Underweight: Consult with a healthcare provider about healthy weight gain strategies.
- Healthy: Maintain your current lifestyle with balanced diet and regular exercise.
- Overweight: Consider lifestyle modifications to reduce waist circumference.
- Obese: Strongly recommended to consult with healthcare providers for weight management.

Note: This calculator provides an estimate and should not replace professional medical advice.

Generated by: Health Calculator App
`;

    const blob = new Blob([report], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `waist-to-height-ratio-report-${new Date().toLocaleDateString().replace(/\//g, '-')}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6">
      <Card>
        <CardHeader>
          <CardTitle>Waist-to-Height Ratio Calculator</CardTitle>
          <CardDescription>
            Calculate your waist-to-height ratio (WHtR), a measure of central obesity and health risk that may be more predictive than BMI.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <Tabs value={system} onValueChange={(v) => setSystem(v as "metric" | "imperial")}>
            <TabsList className="grid w-full grid-cols-2">
              <TabsTrigger value="metric">Metric</TabsTrigger>
              <TabsTrigger value="imperial">Imperial</TabsTrigger>
            </TabsList>
            <TabsContent value="metric" className="space-y-4">
              <CalculatorNumberInput
                label="Waist Circumference"
                value={waistCm}
                onChange={setWaistCm}
                min={50}
                max={200}
                step={0.1}
                unit="cm"
                description="Measure at navel level"
                required
              />
              <CalculatorNumberInput
                label="Height"
                value={heightCm}
                onChange={setHeightCm}
                min={120}
                max={250}
                step={0.1}
                unit="cm"
                required
              />
            </TabsContent>
            <TabsContent value="imperial" className="space-y-4">
              <CalculatorNumberInput
                label="Waist Circumference"
                value={waistIn}
                onChange={setWaistIn}
                min={20}
                max={80}
                step={0.1}
                unit="inches"
                description="Measure at navel level"
                required
              />
              <div className="grid grid-cols-2 gap-4">
                <CalculatorNumberInput
                  label="Height (feet)"
                  value={heightFt}
                  onChange={setHeightFt}
                  min={3}
                  max={8}
                  step={1}
                  unit="ft"
                  required
                />
                <CalculatorNumberInput
                  label="Height (inches)"
                  value={heightIn}
                  onChange={setHeightIn}
                  min={0}
                  max={11}
                  step={1}
                  unit="in"
                  required
                />
              </div>
            </TabsContent>
          </Tabs>
        </CardContent>
      </Card>

      {ratio !== null && (
        <CalculatorResult 
          title="Your Waist-to-Height Ratio Result"
          onDownload={downloadReport}
        >
          <div className="space-y-4">
            <div className="flex flex-col items-center justify-center">
              <div className="text-center">
                <div className="text-4xl font-bold">{ratio}</div>
                <div className="text-sm text-muted-foreground mt-1">Waist-to-Height Ratio</div>
              </div>
              
              <div className="mt-2 text-center">
                <div className={`text-xl font-medium ${getCategoryColor()}`}>
                  {category}
                </div>
                <div className="text-sm text-muted-foreground">Health Category</div>
              </div>
            </div>
            
            <ResultAlert type={
              category === "Healthy" ? "success" : 
              category === "Underweight" ? "info" :
              category === "Overweight" ? "warning" : "error"
            } title={`Health Assessment: ${category}`}>
              <p>
                According to your waist-to-height ratio, you are classified as <strong>{category.toLowerCase()}</strong>.
                {category === "Healthy" ? " This is an ideal range for health outcomes." : ""}
                {category === "Underweight" ? " This may indicate insufficient weight for your height." : ""}
                {category === "Overweight" ? " This indicates excess weight that may pose health risks." : ""}
                {category === "Obese" ? " This indicates significant excess weight that poses substantial health risks." : ""}
              </p>
            </ResultAlert>
            
            <div className="text-sm text-muted-foreground">
              <p className="font-medium">Interpretation:</p>
              <ul className="list-disc list-inside mt-1">
                <li><span className="font-medium">Below 0.4:</span> Underweight</li>
                <li><span className="font-medium">0.4 to 0.49:</span> Healthy</li>
                <li><span className="font-medium">0.5 to 0.59:</span> Overweight</li>
                <li><span className="font-medium">0.6 and above:</span> Obese</li>
              </ul>
              
              <p className="mt-3 font-medium">What this means:</p>
              <p className="mt-1">
                The waist-to-height ratio is a simple measurement for assessing health risk based on central obesity. Studies suggest it may be a better predictor of health risks than BMI.
              </p>
              
              <p className="mt-3 font-medium">General guideline:</p>
              <p className="mt-1 italic">
                "Keep your waist circumference to less than half your height."
              </p>
            </div>
          </div>
        </CalculatorResult>
      )}
    </div>
  );
}
